a = input ('Digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Só tem maíusculas?', a.isupper())
print('Só tem minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
